version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: x3enos/time_tracker:development
    command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
    container_name: web
    tty: true
    stdin_open: true
    entrypoint: /var/www/time_tracker/docker-entrypoint.sh
    volumes:
      - .:/var/www/time_tracker
      - ./extension:/var/www/time_tracker_extension/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    env_file:
      - .env.development.local

  mailcatcher:
    image: instructure/mailcatcher
    environment:
      VIRTUAL_HOST: mail.example.docker
      VIRTUAL_PORT: 8080
    ports:
      - "8080:8080"
      - "1025:1025"

  polling_service:
    image: x3enos/time_tracker:development
    command: bundle exec rake time_tracker_extension:telegram_bot_poller
    container_name: polling_service
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/time_tracker
      - ./extension:/var/www/time_tracker_extension/
    depends_on:
      - db
    env_file:
      - .env.development.local
