version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: x3enos/time_tracker:development
    command: "bin/bundle exec rails s -p 3000 -b 0.0.0.0"
    container_name: web
    tty: true
    stdin_open: true
    entrypoint: /var/www/time_tracker/docker-entrypoint.sh
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/time_tracker
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.development.local
